# Generated by Django 4.2.7 on 2026-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
